name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
      value: |
        If you don't know replace this with "NA"
      render: bash
    validations:
      required: true
  - type: input
    id: command
    attributes:
      label: Command?
      description: What command did you run?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Have you checked if this bug has already been reported?
      options:
        - label: I have checked and this bug doesn't exist.
          required: true
